<?php
return array(
		'buildFatherType'=>array(
				1=>'小区',
				2=>'新盘'
		),
		'buildTypeNew'=>array(
				1=>'住宅',
				2=>'商铺',
				3=>'写字楼',
				4=>'别墅',
		),
		'buildType'=>array(
				1=>'住宅',
				2=>'商铺',
				3=>'写字楼',
				4=>'别墅',
				5=>'厂房'
		),
		'buildSellRent'=>array(
				1=>'出租',
				2=>'出售'
		),
		'2handHousePayInfo'=>array(
				1=>'商品房',
				2=>'微利房',
				3=>'军产房',
				4=>'集资房',
				5=>'农民房',
				6=>'福利房'
		),
		'2handHouseType'=>array(
				1=>'普通住宅',
			    2=>'高档住宅',
			    3=>'酒店式公寓 ',
			    4=>'集资房'		
		),
		'2handHouseForward'=>array(				
			   	1=>'东',
			    2=>'南',    
			    3=>'西',    
			    4=>'北',  
			    5=>'东南',
			    6=>'西南',    
			    7=>'西北',    
			    8=>'东北',
			    9=>'南北',
			    10=>'东西'
		),
		'2handHouseFitment'=>array(			
			  	1=>'豪华装修',     
			    2=>'精装修',    
			    3=>'中等装修',    
			    4=>'简装修',  
			    5=>'毛坯'
		),
		'2handHouseBaseService'=>array(		
			    1=>'煤气/天然气',
			    2=>'暖气',
			    3=>'电梯',
			    4=>'车位/车库',
			    5=>'储藏室/地下室',
			    6=>'花园/小院',
			    7=>'露台',
			    8=>'阁楼'
		),
		'2handHouseRentType'=>array(	
	            1=>'整租',
	            2=>'合租'
		),
		'2handHouseRentRoomType'=>array(	
		        1=>'主卧',
		        2=>'次卧',
		        3=>'床位',
		        4=>'隔断间'
		),
		'2handHouseRentDetail'=>array(	
	            1=>'性别不限',
	            2=>'限女生',
	            3=>'限男生',
	            4=>'限夫妻'
		),
		'2handHousePayment'=>array(	
				1=>'押付',
				2=>'面议'
		),
		'2handHousePayDetailY'=>array(	
				0=>'零',
				1=>'一个月',
				2=>'两个月',
				3=>'三个月',
				6=>'六个月'
		),
		'2handHousePayDetailF'=>array(	
                1=>'一个月',
                2=>'两个月',
                3=>'三个月',
                6=>'六个月',
                12=>'十二个月'
		),
		'2handHouseLookTime'=>array(	
			  	1=>'随时看房',     
			    2=>'非工作时间',    
			    3=>'电话预约'   
		),
		'2handOfficeType'=>array(	
			    1=>'纯写字楼',     
			    2=>'商住楼',
			    3=>'商业综合体楼',
			    4=>'酒店写字楼'
		),
		'2handOfficeDivision'=>array(	
			    1=>'可分割',     
			    2=>'不可分割'
		),
		'2handOfficeFitment'=>array(
			    1=>'精装修',     
			    2=>'简装修',
			    3=>'毛坯'
		),
		'2handOfficeLevel'=>array(
			    1=>'甲级',     
			    2=>'乙级',
			    3=>'丙级',
			    4=>'其它'
		),
		'2handShopsType'=>array(
			    1=>'住宅底商',     
			    2=>'商业街商铺',    
			    3=>'写字楼配套底商',    
			    4=>'购物中心/百货',  
			    5=>'其他'
		),
		'2handShopsDivision'=>array(
			    1=>'可分割',     
			    2=>'不可分割'
		),
		'2handShopsFitment'=>array(
			    1=>'精装修',     
			    2=>'简装修',
			    3=>'毛坯'
		),
		'2handShopsBaseService'=>array(
			    1=>'客梯',
			    2=>'货梯',
			    3=>'扶梯',
			    4=>'暖气',
			    5=>'空调',
			    6=>'停车位',
			    7=>'水',
			    8=>'燃气',
			    9=>'网络'
		),
		'2handShopsAimOperastion'=>array(
			   	1=>'百货超市',
			    2=>'酒店宾馆',
			    3=>'家居建材',
			    4=>'服饰鞋包',
			    5=>'生活服务',
			    6=>'美容美发',
			    7=>'餐饮美食',
			    8=>'休闲娱乐',
			    9=>'其他'
		),
		'2handShopsRentPriceUnit'=>array(
			   	1=>'元/平米·天',
			    2=>'元/平米·月',
			    3=>'元/月'
		),
		'2handVillaBuildForm'=>array(
				1=>'独栋', 
				2=>'联排',  
				3=>'双拼', 
				4=>'叠加'
		),
		'2handVillaForward'=>array(
				1=>'东', 
				2=>'西',  
				3=>'南', 
				4=>'北' 
		),
		'2handVillaCellarType'=>array(
				1=>'全明', 
				2=>'半明', 
				3=>'暗'
		),
		'2handVillaFitment'=>array(
			  	1=>'豪华装修',     
			    2=>'精装修',    
			    3=>'中等装修',    
			    4=>'简装修',  
			    5=>'毛坯'
		),
		'2handVillaBaseService'=>array(
			    1=>'煤气/天然气',
			    2=>'暖气',
			    3=>'电梯',
			    4=>'车位/车库',
			    5=>'储藏室/地下室',
			    6=>'花园/小院'
		),
		'2handVillaLookTime'=>array(	
			  	1=>'随时看房',     
			    2=>'非工作时间',    
			    3=>'电话预约'   
		),
		'2handVillaPayment'=>array(	
				1=>'押付',
				2=>'面议'
		),
		'2handVillaPayDetailY'=>array(	
				0=>'零',
				1=>'一个月',
				2=>'两个月',
				3=>'三个月',
				6=>'六个月'
		),
		'2handVillaPayDetailF'=>array(	
                1=>'一个月',
                2=>'两个月',
                3=>'三个月',
                6=>'六个月',
                12=>'十二个月'
		),
		'2handVillaRentType'=>array(	
                1=>'整租',
                2=>'合租'
		),			
		'2handFactoryType'=>array(	
			    1=>'独立厂房',     
			    2=>'工业园',    
			    3=>'开发区',    
			    4=>'产业基地',  
			    5=>'其他'
		),
		'2handFactoryPayInfo'=>array(	
				1=>'国有土地证',
				2=>'集体土地证'
		),
		'2handFactoryIncludFee'=>array(	
				1=>'是',
				2=>'否'
		),
		'2handFactoryPayment'=>array(	
				1=>'押付',
				2=>'面议'
		),
		'2handFactoryPayDetailY'=>array(	
				0=>'零',
				1=>'一个月',
				2=>'两个月',
				3=>'三个月',
				6=>'六个月'
		),
		'2handFactoryPayDetailF'=>array(	
                1=>'一个月',
                2=>'两个月',
                3=>'三个月',
                6=>'六个月',
                12=>'十二个月'
		),
		'2handConfig'=>array(	
               'REFRESH_COUNT_USER'=>10,
               'REFRESH_COUNT_AGENT'=>60,
               'PROPERTY_COUNT_LEASE_USER'=>10,
               'PROPERTY_COUNT_SALE_USER'=>10,
               'PROPERTY_COUNT_LEASE_AGENT'=>60,
               'PROPERTY_COUNT_SALE_AGENT'=>60,
			   'DAYS_TO_BE_EXPIRED'=>15,
			   'DAYS_SOON_TO_BE_EXPIRED'=>12
		)								    						 
);